global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files: null
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: node-exporter
  static_configs:
  - targets:
    - localhost:9100
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9008
- job_name: dataSupplier
  scrape_interval: 5s
  metrics_path: /ops/prometheus
  static_configs:
  - targets:
    - localhost:8082
- job_name: dataConsumer
  scrape_interval: 5s
  metrics_path: /ops/prometheus
  static_configs:
  - targets:
    - localhost:8084
- job_name: rabbitmq
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9999