version: '3.0'
services:
  exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    ports:
      - 9100:9100
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    restart: unless-stopped
    network_mode: host
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    restart: always
    ports:
    - 9090:9090
    volumes:
    - "${PROMETHEUS_DATA_DIR:-prometheus}:/prometheus"
    - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    - "./prometheus/alert.rules:/etc/prometheus/alert.rules"
    depends_on:
    - exporter
    - cadvisor
    - alertmanager
    network_mode: host
  grafana:
    image: "grafana/grafana:5.3.2"
    container_name: dashboards_grafana
    hostname: dashboards_grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      #GF_AUTH_ANONYMOUS_ENABLED: "true"
    restart: unless-stopped
    volumes:
     # - "${GRAFANA_DATA_DIR:-grafana}:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
     # - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
     # - "./grafana/dashboards:/var/lib/grafana/dashboards:ro"
    ports:
    - 80:3000
    depends_on:
    - prometheus
  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager/alertmanager.yml:/alertmanager.yml
    network_mode: host

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    ports:
    - 9008:8080
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "15672:15672"
     - "5672:5672"
     - "9419:9419"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    ports:
      - 9999:9419
    environment:
      PUBLISH_PORT: 9419
      RABBIT_CAPABILITIES: bert,no_sort
      RABBIT_USER: test
      RABBIT_PASSWORD: password
      RABBIT_URL: http://rabbitmq:15672
    links:
      - rabbitmq
networks:
  sample:
    driver: bridge
volumes:
  grafana:
  prometheus:
